# Make sure to add any non-development-rellated changes to ./Dockerfile
# as well for the production version of this dockerfile.

FROM golang:1.16

WORKDIR /app
COPY ./sandbox /app
RUN go mod tidy
RUN go build /app/sandbox.go

# Copy the .env file to force Tilt to re-build the container.
# This isn't actually used in the development environment;
# instead, the ConfigMap mounts env variables in the pod
COPY ./sandbox/.env /tmp/.env

CMD /app/sandbox
