apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox
  labels:
    app: sandbox
spec:
  selector:
    matchLabels:
      app: sandbox
  template:
    metadata:
      labels:
        app: sandbox
    spec:
      containers:
        - name: sandbox
          image: "{{prefix}}sandbox:{{tag}}"
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
          env:
          - name: HTTP_PROXY
            valueFrom:
              configMapKeyRef:
                name: sandbox-config
                key: HTTP_PROXY
          - name: HTTPS_PROXY
            valueFrom:
              configMapKeyRef:
                name: sandbox-config
                key: HTTPS_PROXY
          - name: http_proxy
            valueFrom:
              configMapKeyRef:
                name: sandbox-config
                key: http_proxy
          - name: https_proxy
            valueFrom:
              configMapKeyRef:
                name: sandbox-config
                key: https_proxy
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: sandbox
spec:
  type: ClusterIP
  selector:
    app: sandbox
  ports:
  - protocol: TCP
    port: 1337
    targetPort: 1337
