# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='manager.proto',
  package='Manager',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rmanager.proto\x12\x07Manager\"\x11\n\x0fRegisterRequest\"\x13\n\x11GuildCountRequest\"\x11\n\x0f\x43heckInResponse\"\x12\n\x10\x41llGuildsRequest\"\x10\n\x0eUpdateResponse\"2\n\tShardInfo\x12\x10\n\x08shard_id\x18\x01 \x01(\r\x12\x13\n\x0bshard_count\x18\x02 \x01(\r\"4\n\tGuildInfo\x12\x13\n\x0bguild_count\x18\x01 \x01(\r\x12\x12\n\nuser_count\x18\x02 \x01(\r\"\x1b\n\x07ShardID\x12\x10\n\x08shard_id\x18\x01 \x01(\r\"F\n\x04\x46ile\x12\x10\n\x08location\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x66iletype\x18\x03 \x01(\t\x12\x0c\n\x04\x66ile\x18\x04 \x01(\x0c\"\x12\n\x03Url\x12\x0b\n\x03Url\x18\x01 \x01(\t\"\xf9\x02\n\x05Guild\x12\x10\n\x08shard_id\x18\x01 \x01(\r\x12\n\n\x02id\x18\x02 \x01(\x06\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04icon\x18\x04 \x01(\t\x12\x0e\n\x06splash\x18\x05 \x01(\t\x12\x10\n\x08owner_id\x18\x06 \x01(\x06\x12\x0e\n\x06region\x18\x07 \x01(\t\x12\x13\n\x0b\x61\x66k_timeout\x18\x08 \x01(\r\x12\x13\n\x0bunavailable\x18\t \x01(\x08\x12\x13\n\x0bmax_members\x18\n \x01(\x05\x12\x0e\n\x06\x62\x61nner\x18\x0b \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x0c \x01(\t\x12\x11\n\tmfa_level\x18\r \x01(\x05\x12\x14\n\x0cpremium_tier\x18\x0e \x01(\r\x12\"\n\x1apremium_subscription_count\x18\x0f \x01(\x05\x12\x18\n\x10preferred_locale\x18\x10 \x01(\t\x12\x14\n\x0cmember_count\x18\x11 \x01(\x05\x12\x11\n\tadmin_ids\x18\x12 \x03(\x06\x12\x10\n\x08\x66\x65\x61tures\x18\x13 \x03(\t2\xea\x02\n\x07Manager\x12:\n\x08register\x12\x18.Manager.RegisterRequest\x1a\x12.Manager.ShardInfo\"\x00\x12?\n\x0bguild_count\x12\x1a.Manager.GuildCountRequest\x1a\x12.Manager.GuildInfo\"\x00\x12\x37\n\x07\x63heckin\x12\x10.Manager.ShardID\x1a\x18.Manager.CheckInResponse\"\x00\x12/\n\x0cpublish_file\x12\r.Manager.File\x1a\x0c.Manager.Url\"\x00(\x01\x12;\n\nall_guilds\x12\x19.Manager.AllGuildsRequest\x1a\x0e.Manager.Guild\"\x00\x30\x01\x12;\n\x0cguild_update\x12\x0e.Manager.Guild\x1a\x17.Manager.UpdateResponse\"\x00(\x01\x62\x06proto3'
)




_REGISTERREQUEST = _descriptor.Descriptor(
  name='RegisterRequest',
  full_name='Manager.RegisterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=43,
)


_GUILDCOUNTREQUEST = _descriptor.Descriptor(
  name='GuildCountRequest',
  full_name='Manager.GuildCountRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=64,
)


_CHECKINRESPONSE = _descriptor.Descriptor(
  name='CheckInResponse',
  full_name='Manager.CheckInResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=83,
)


_ALLGUILDSREQUEST = _descriptor.Descriptor(
  name='AllGuildsRequest',
  full_name='Manager.AllGuildsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=103,
)


_UPDATERESPONSE = _descriptor.Descriptor(
  name='UpdateResponse',
  full_name='Manager.UpdateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=121,
)


_SHARDINFO = _descriptor.Descriptor(
  name='ShardInfo',
  full_name='Manager.ShardInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shard_id', full_name='Manager.ShardInfo.shard_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shard_count', full_name='Manager.ShardInfo.shard_count', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=173,
)


_GUILDINFO = _descriptor.Descriptor(
  name='GuildInfo',
  full_name='Manager.GuildInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='guild_count', full_name='Manager.GuildInfo.guild_count', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_count', full_name='Manager.GuildInfo.user_count', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=227,
)


_SHARDID = _descriptor.Descriptor(
  name='ShardID',
  full_name='Manager.ShardID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shard_id', full_name='Manager.ShardID.shard_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=229,
  serialized_end=256,
)


_FILE = _descriptor.Descriptor(
  name='File',
  full_name='Manager.File',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='Manager.File.location', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='Manager.File.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filetype', full_name='Manager.File.filetype', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file', full_name='Manager.File.file', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=328,
)


_URL = _descriptor.Descriptor(
  name='Url',
  full_name='Manager.Url',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Url', full_name='Manager.Url.Url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=330,
  serialized_end=348,
)


_GUILD = _descriptor.Descriptor(
  name='Guild',
  full_name='Manager.Guild',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shard_id', full_name='Manager.Guild.shard_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='Manager.Guild.id', index=1,
      number=2, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='Manager.Guild.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='icon', full_name='Manager.Guild.icon', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='splash', full_name='Manager.Guild.splash', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='owner_id', full_name='Manager.Guild.owner_id', index=5,
      number=6, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='region', full_name='Manager.Guild.region', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='afk_timeout', full_name='Manager.Guild.afk_timeout', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unavailable', full_name='Manager.Guild.unavailable', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_members', full_name='Manager.Guild.max_members', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='banner', full_name='Manager.Guild.banner', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='Manager.Guild.description', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mfa_level', full_name='Manager.Guild.mfa_level', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='premium_tier', full_name='Manager.Guild.premium_tier', index=13,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='premium_subscription_count', full_name='Manager.Guild.premium_subscription_count', index=14,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='preferred_locale', full_name='Manager.Guild.preferred_locale', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='member_count', full_name='Manager.Guild.member_count', index=16,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='admin_ids', full_name='Manager.Guild.admin_ids', index=17,
      number=18, type=6, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='features', full_name='Manager.Guild.features', index=18,
      number=19, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=728,
)

DESCRIPTOR.message_types_by_name['RegisterRequest'] = _REGISTERREQUEST
DESCRIPTOR.message_types_by_name['GuildCountRequest'] = _GUILDCOUNTREQUEST
DESCRIPTOR.message_types_by_name['CheckInResponse'] = _CHECKINRESPONSE
DESCRIPTOR.message_types_by_name['AllGuildsRequest'] = _ALLGUILDSREQUEST
DESCRIPTOR.message_types_by_name['UpdateResponse'] = _UPDATERESPONSE
DESCRIPTOR.message_types_by_name['ShardInfo'] = _SHARDINFO
DESCRIPTOR.message_types_by_name['GuildInfo'] = _GUILDINFO
DESCRIPTOR.message_types_by_name['ShardID'] = _SHARDID
DESCRIPTOR.message_types_by_name['File'] = _FILE
DESCRIPTOR.message_types_by_name['Url'] = _URL
DESCRIPTOR.message_types_by_name['Guild'] = _GUILD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegisterRequest = _reflection.GeneratedProtocolMessageType('RegisterRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERREQUEST,
  '__module__' : 'manager_pb2'
  # @@protoc_insertion_point(class_scope:Manager.RegisterRequest)
  })
_sym_db.RegisterMessage(RegisterRequest)

GuildCountRequest = _reflection.GeneratedProtocolMessageType('GuildCountRequest', (_message.Message,), {
  'DESCRIPTOR' : _GUILDCOUNTREQUEST,
  '__module__' : 'manager_pb2'
  # @@protoc_insertion_point(class_scope:Manager.GuildCountRequest)
  })
_sym_db.RegisterMessage(GuildCountRequest)

CheckInResponse = _reflection.GeneratedProtocolMessageType('CheckInResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHECKINRESPONSE,
  '__module__' : 'manager_pb2'
  # @@protoc_insertion_point(class_scope:Manager.CheckInResponse)
  })
_sym_db.RegisterMessage(CheckInResponse)

AllGuildsRequest = _reflection.GeneratedProtocolMessageType('AllGuildsRequest', (_message.Message,), {
  'DESCRIPTOR' : _ALLGUILDSREQUEST,
  '__module__' : 'manager_pb2'
  # @@protoc_insertion_point(class_scope:Manager.AllGuildsRequest)
  })
_sym_db.RegisterMessage(AllGuildsRequest)

UpdateResponse = _reflection.GeneratedProtocolMessageType('UpdateResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATERESPONSE,
  '__module__' : 'manager_pb2'
  # @@protoc_insertion_point(class_scope:Manager.UpdateResponse)
  })
_sym_db.RegisterMessage(UpdateResponse)

ShardInfo = _reflection.GeneratedProtocolMessageType('ShardInfo', (_message.Message,), {
  'DESCRIPTOR' : _SHARDINFO,
  '__module__' : 'manager_pb2'
  # @@protoc_insertion_point(class_scope:Manager.ShardInfo)
  })
_sym_db.RegisterMessage(ShardInfo)

GuildInfo = _reflection.GeneratedProtocolMessageType('GuildInfo', (_message.Message,), {
  'DESCRIPTOR' : _GUILDINFO,
  '__module__' : 'manager_pb2'
  # @@protoc_insertion_point(class_scope:Manager.GuildInfo)
  })
_sym_db.RegisterMessage(GuildInfo)

ShardID = _reflection.GeneratedProtocolMessageType('ShardID', (_message.Message,), {
  'DESCRIPTOR' : _SHARDID,
  '__module__' : 'manager_pb2'
  # @@protoc_insertion_point(class_scope:Manager.ShardID)
  })
_sym_db.RegisterMessage(ShardID)

File = _reflection.GeneratedProtocolMessageType('File', (_message.Message,), {
  'DESCRIPTOR' : _FILE,
  '__module__' : 'manager_pb2'
  # @@protoc_insertion_point(class_scope:Manager.File)
  })
_sym_db.RegisterMessage(File)

Url = _reflection.GeneratedProtocolMessageType('Url', (_message.Message,), {
  'DESCRIPTOR' : _URL,
  '__module__' : 'manager_pb2'
  # @@protoc_insertion_point(class_scope:Manager.Url)
  })
_sym_db.RegisterMessage(Url)

Guild = _reflection.GeneratedProtocolMessageType('Guild', (_message.Message,), {
  'DESCRIPTOR' : _GUILD,
  '__module__' : 'manager_pb2'
  # @@protoc_insertion_point(class_scope:Manager.Guild)
  })
_sym_db.RegisterMessage(Guild)



_MANAGER = _descriptor.ServiceDescriptor(
  name='Manager',
  full_name='Manager.Manager',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=731,
  serialized_end=1093,
  methods=[
  _descriptor.MethodDescriptor(
    name='register',
    full_name='Manager.Manager.register',
    index=0,
    containing_service=None,
    input_type=_REGISTERREQUEST,
    output_type=_SHARDINFO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='guild_count',
    full_name='Manager.Manager.guild_count',
    index=1,
    containing_service=None,
    input_type=_GUILDCOUNTREQUEST,
    output_type=_GUILDINFO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='checkin',
    full_name='Manager.Manager.checkin',
    index=2,
    containing_service=None,
    input_type=_SHARDID,
    output_type=_CHECKINRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='publish_file',
    full_name='Manager.Manager.publish_file',
    index=3,
    containing_service=None,
    input_type=_FILE,
    output_type=_URL,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='all_guilds',
    full_name='Manager.Manager.all_guilds',
    index=4,
    containing_service=None,
    input_type=_ALLGUILDSREQUEST,
    output_type=_GUILD,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='guild_update',
    full_name='Manager.Manager.guild_update',
    index=5,
    containing_service=None,
    input_type=_GUILD,
    output_type=_UPDATERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MANAGER)

DESCRIPTOR.services_by_name['Manager'] = _MANAGER

# @@protoc_insertion_point(module_scope)
