# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sandbox.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sandbox.proto',
  package='sandbox',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rsandbox.proto\x12\x07sandbox\"}\n\x0eStarlarkScript\x12\x0e\n\x06script\x18\x01 \x01(\t\x12\x17\n\x0ftrigger_message\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\r\n\x05\x63ount\x18\x04 \x01(\x04\x12\x10\n\x08\x63\x61ptures\x18\x05 \x03(\t\x12\x11\n\targuments\x18\x06 \x03(\t\"<\n\x0cScriptOutput\x12\x0e\n\x06output\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\r\n\x05\x65rrno\x18\x03 \x01(\x04\x32P\n\x07Sandbox\x12\x45\n\x11RunStarlarkScript\x12\x17.sandbox.StarlarkScript\x1a\x15.sandbox.ScriptOutput\"\x00\x62\x06proto3'
)




_STARLARKSCRIPT = _descriptor.Descriptor(
  name='StarlarkScript',
  full_name='sandbox.StarlarkScript',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='script', full_name='sandbox.StarlarkScript.script', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trigger_message', full_name='sandbox.StarlarkScript.trigger_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='author', full_name='sandbox.StarlarkScript.author', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='sandbox.StarlarkScript.count', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='captures', full_name='sandbox.StarlarkScript.captures', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arguments', full_name='sandbox.StarlarkScript.arguments', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=151,
)


_SCRIPTOUTPUT = _descriptor.Descriptor(
  name='ScriptOutput',
  full_name='sandbox.ScriptOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='output', full_name='sandbox.ScriptOutput.output', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='sandbox.ScriptOutput.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='errno', full_name='sandbox.ScriptOutput.errno', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=213,
)

DESCRIPTOR.message_types_by_name['StarlarkScript'] = _STARLARKSCRIPT
DESCRIPTOR.message_types_by_name['ScriptOutput'] = _SCRIPTOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StarlarkScript = _reflection.GeneratedProtocolMessageType('StarlarkScript', (_message.Message,), {
  'DESCRIPTOR' : _STARLARKSCRIPT,
  '__module__' : 'sandbox_pb2'
  # @@protoc_insertion_point(class_scope:sandbox.StarlarkScript)
  })
_sym_db.RegisterMessage(StarlarkScript)

ScriptOutput = _reflection.GeneratedProtocolMessageType('ScriptOutput', (_message.Message,), {
  'DESCRIPTOR' : _SCRIPTOUTPUT,
  '__module__' : 'sandbox_pb2'
  # @@protoc_insertion_point(class_scope:sandbox.ScriptOutput)
  })
_sym_db.RegisterMessage(ScriptOutput)



_SANDBOX = _descriptor.ServiceDescriptor(
  name='Sandbox',
  full_name='sandbox.Sandbox',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=215,
  serialized_end=295,
  methods=[
  _descriptor.MethodDescriptor(
    name='RunStarlarkScript',
    full_name='sandbox.Sandbox.RunStarlarkScript',
    index=0,
    containing_service=None,
    input_type=_STARLARKSCRIPT,
    output_type=_SCRIPTOUTPUT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SANDBOX)

DESCRIPTOR.services_by_name['Sandbox'] = _SANDBOX

# @@protoc_insertion_point(module_scope)
