# Create minimal deployment
# with just the service binary included

FROM debian:buster-slim
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -q \
    && apt-get install -y -q "libssl1.1" "tini" "libpq-dev" \
    && rm -rf /var/lib/apt/lists/*
COPY feature-gate/target/debug/feature-gate /usr/bin/feature-gate
ENV RUST_BACKTRACE=1
ENTRYPOINT ["/usr/bin/feature-gate"]
