# Fill out and rename to secret.yaml
---
# Ignore these lines ===============
apiVersion: v1
kind: Secret
metadata:
  name: architus-secret
stringData:
# Stop ignoring ====================

# Fill in the following key: value
# pairs with the appropriate values
  NUM_SHARDS: "1"
  bot_token:
  db_user: "autbot"
  db_pass: "autism"
  client_id:
  client_secret:
  application_public_key:
  domain_name: "develop.archit.us"
  jwt_secret: "0ijr2bQCMTPmEg3YQ1QnMlLMKetyguAHafWr_pqNlT0"
  uwsgi_protocol: http
  alphavantage_api_key:
  scraper_bot_token:
  spotify_client_secret:
  twitch_client_id:
  twitch_client_secret:
  twitch_hub_secret:
