apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox
  labels:
    app: sandbox
spec:
  selector:
    matchLabels:
      app: sandbox
  template:
    metadata:
      labels:
        app: sandbox
    spec:
      containers:
        - name: sandbox
          image: sandbox-image
          envFrom:
          - secretRef:
              name: architus-secret
---
apiVersion: v1
kind: Service
metadata:
  name: sandbox
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: sandbox
  ports:
  - port: 1337
    targetPort: 1337