# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: feature-gate.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='feature-gate.proto',
  package='featuregate',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x66\x65\x61ture-gate.proto\x12\x0b\x66\x65\x61turegate\"%\n\x07\x46\x65\x61ture\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04open\x18\x02 \x01(\x08\"\x1b\n\x0b\x46\x65\x61tureName\x12\x0c\n\x04name\x18\x01 \x01(\t\"9\n\x0f\x46\x65\x61tureAddition\x12\x14\n\x0c\x66\x65\x61ture_name\x18\x01 \x01(\t\x12\x10\n\x08guild_id\x18\x02 \x01(\x06\"8\n\x0e\x46\x65\x61tureRemoval\x12\x14\n\x0c\x66\x65\x61ture_name\x18\x01 \x01(\t\x12\x10\n\x08guild_id\x18\x02 \x01(\x06\"6\n\x0cGuildFeature\x12\x14\n\x0c\x66\x65\x61ture_name\x18\x01 \x01(\t\x12\x10\n\x08guild_id\x18\x02 \x01(\x06\"5\n\nBatchCheck\x12\x14\n\x0c\x66\x65\x61ture_name\x18\x01 \x01(\t\x12\x11\n\tguild_ids\x18\x02 \x03(\x06\"\x19\n\x05Guild\x12\x10\n\x08guild_id\x18\x01 \x01(\x06\"\r\n\x0b\x46\x65\x61tureList\"!\n\x0e\x43reationResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1e\n\x0eOpennessResult\x12\x0c\n\x04open\x18\x01 \x01(\x08\"\x1c\n\tAddResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1f\n\x0cRemoveResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\"$\n\rFeatureResult\x12\x13\n\x0bhas_feature\x18\x01 \x01(\x08\"\'\n\x10\x42\x61tchCheckResult\x12\x13\n\x0bhas_feature\x18\x01 \x03(\x08\x32\xd0\x04\n\x0b\x46\x65\x61tureGate\x12\x42\n\rCreateFeature\x12\x14.featuregate.Feature\x1a\x1b.featuregate.CreationResult\x12\x46\n\rCheckOpenness\x12\x18.featuregate.FeatureName\x1a\x1b.featuregate.OpennessResult\x12G\n\x0f\x41\x64\x64GuildFeature\x12\x1c.featuregate.FeatureAddition\x1a\x16.featuregate.AddResult\x12L\n\x12RemoveGuildFeature\x12\x1b.featuregate.FeatureRemoval\x1a\x19.featuregate.RemoveResult\x12J\n\x11\x43heckGuildFeature\x12\x19.featuregate.GuildFeature\x1a\x1a.featuregate.FeatureResult\x12Q\n\x17\x42\x61tchCheckGuildFeatures\x12\x17.featuregate.BatchCheck\x1a\x1d.featuregate.BatchCheckResult\x12?\n\x0bGetFeatures\x12\x18.featuregate.FeatureList\x1a\x14.featuregate.Feature0\x01\x12>\n\x10GetGuildFeatures\x12\x12.featuregate.Guild\x1a\x14.featuregate.Feature0\x01\x62\x06proto3'
)




_FEATURE = _descriptor.Descriptor(
  name='Feature',
  full_name='featuregate.Feature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='featuregate.Feature.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='open', full_name='featuregate.Feature.open', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=72,
)


_FEATURENAME = _descriptor.Descriptor(
  name='FeatureName',
  full_name='featuregate.FeatureName',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='featuregate.FeatureName.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=101,
)


_FEATUREADDITION = _descriptor.Descriptor(
  name='FeatureAddition',
  full_name='featuregate.FeatureAddition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature_name', full_name='featuregate.FeatureAddition.feature_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='guild_id', full_name='featuregate.FeatureAddition.guild_id', index=1,
      number=2, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=160,
)


_FEATUREREMOVAL = _descriptor.Descriptor(
  name='FeatureRemoval',
  full_name='featuregate.FeatureRemoval',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature_name', full_name='featuregate.FeatureRemoval.feature_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='guild_id', full_name='featuregate.FeatureRemoval.guild_id', index=1,
      number=2, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=218,
)


_GUILDFEATURE = _descriptor.Descriptor(
  name='GuildFeature',
  full_name='featuregate.GuildFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature_name', full_name='featuregate.GuildFeature.feature_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='guild_id', full_name='featuregate.GuildFeature.guild_id', index=1,
      number=2, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=274,
)


_BATCHCHECK = _descriptor.Descriptor(
  name='BatchCheck',
  full_name='featuregate.BatchCheck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature_name', full_name='featuregate.BatchCheck.feature_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='guild_ids', full_name='featuregate.BatchCheck.guild_ids', index=1,
      number=2, type=6, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=329,
)


_GUILD = _descriptor.Descriptor(
  name='Guild',
  full_name='featuregate.Guild',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='guild_id', full_name='featuregate.Guild.guild_id', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=331,
  serialized_end=356,
)


_FEATURELIST = _descriptor.Descriptor(
  name='FeatureList',
  full_name='featuregate.FeatureList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=358,
  serialized_end=371,
)


_CREATIONRESULT = _descriptor.Descriptor(
  name='CreationResult',
  full_name='featuregate.CreationResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='featuregate.CreationResult.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=373,
  serialized_end=406,
)


_OPENNESSRESULT = _descriptor.Descriptor(
  name='OpennessResult',
  full_name='featuregate.OpennessResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='open', full_name='featuregate.OpennessResult.open', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=408,
  serialized_end=438,
)


_ADDRESULT = _descriptor.Descriptor(
  name='AddResult',
  full_name='featuregate.AddResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='featuregate.AddResult.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=440,
  serialized_end=468,
)


_REMOVERESULT = _descriptor.Descriptor(
  name='RemoveResult',
  full_name='featuregate.RemoveResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='featuregate.RemoveResult.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=470,
  serialized_end=501,
)


_FEATURERESULT = _descriptor.Descriptor(
  name='FeatureResult',
  full_name='featuregate.FeatureResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='has_feature', full_name='featuregate.FeatureResult.has_feature', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=503,
  serialized_end=539,
)


_BATCHCHECKRESULT = _descriptor.Descriptor(
  name='BatchCheckResult',
  full_name='featuregate.BatchCheckResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='has_feature', full_name='featuregate.BatchCheckResult.has_feature', index=0,
      number=1, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=541,
  serialized_end=580,
)

DESCRIPTOR.message_types_by_name['Feature'] = _FEATURE
DESCRIPTOR.message_types_by_name['FeatureName'] = _FEATURENAME
DESCRIPTOR.message_types_by_name['FeatureAddition'] = _FEATUREADDITION
DESCRIPTOR.message_types_by_name['FeatureRemoval'] = _FEATUREREMOVAL
DESCRIPTOR.message_types_by_name['GuildFeature'] = _GUILDFEATURE
DESCRIPTOR.message_types_by_name['BatchCheck'] = _BATCHCHECK
DESCRIPTOR.message_types_by_name['Guild'] = _GUILD
DESCRIPTOR.message_types_by_name['FeatureList'] = _FEATURELIST
DESCRIPTOR.message_types_by_name['CreationResult'] = _CREATIONRESULT
DESCRIPTOR.message_types_by_name['OpennessResult'] = _OPENNESSRESULT
DESCRIPTOR.message_types_by_name['AddResult'] = _ADDRESULT
DESCRIPTOR.message_types_by_name['RemoveResult'] = _REMOVERESULT
DESCRIPTOR.message_types_by_name['FeatureResult'] = _FEATURERESULT
DESCRIPTOR.message_types_by_name['BatchCheckResult'] = _BATCHCHECKRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Feature = _reflection.GeneratedProtocolMessageType('Feature', (_message.Message,), {
  'DESCRIPTOR' : _FEATURE,
  '__module__' : 'feature_gate_pb2'
  # @@protoc_insertion_point(class_scope:featuregate.Feature)
  })
_sym_db.RegisterMessage(Feature)

FeatureName = _reflection.GeneratedProtocolMessageType('FeatureName', (_message.Message,), {
  'DESCRIPTOR' : _FEATURENAME,
  '__module__' : 'feature_gate_pb2'
  # @@protoc_insertion_point(class_scope:featuregate.FeatureName)
  })
_sym_db.RegisterMessage(FeatureName)

FeatureAddition = _reflection.GeneratedProtocolMessageType('FeatureAddition', (_message.Message,), {
  'DESCRIPTOR' : _FEATUREADDITION,
  '__module__' : 'feature_gate_pb2'
  # @@protoc_insertion_point(class_scope:featuregate.FeatureAddition)
  })
_sym_db.RegisterMessage(FeatureAddition)

FeatureRemoval = _reflection.GeneratedProtocolMessageType('FeatureRemoval', (_message.Message,), {
  'DESCRIPTOR' : _FEATUREREMOVAL,
  '__module__' : 'feature_gate_pb2'
  # @@protoc_insertion_point(class_scope:featuregate.FeatureRemoval)
  })
_sym_db.RegisterMessage(FeatureRemoval)

GuildFeature = _reflection.GeneratedProtocolMessageType('GuildFeature', (_message.Message,), {
  'DESCRIPTOR' : _GUILDFEATURE,
  '__module__' : 'feature_gate_pb2'
  # @@protoc_insertion_point(class_scope:featuregate.GuildFeature)
  })
_sym_db.RegisterMessage(GuildFeature)

BatchCheck = _reflection.GeneratedProtocolMessageType('BatchCheck', (_message.Message,), {
  'DESCRIPTOR' : _BATCHCHECK,
  '__module__' : 'feature_gate_pb2'
  # @@protoc_insertion_point(class_scope:featuregate.BatchCheck)
  })
_sym_db.RegisterMessage(BatchCheck)

Guild = _reflection.GeneratedProtocolMessageType('Guild', (_message.Message,), {
  'DESCRIPTOR' : _GUILD,
  '__module__' : 'feature_gate_pb2'
  # @@protoc_insertion_point(class_scope:featuregate.Guild)
  })
_sym_db.RegisterMessage(Guild)

FeatureList = _reflection.GeneratedProtocolMessageType('FeatureList', (_message.Message,), {
  'DESCRIPTOR' : _FEATURELIST,
  '__module__' : 'feature_gate_pb2'
  # @@protoc_insertion_point(class_scope:featuregate.FeatureList)
  })
_sym_db.RegisterMessage(FeatureList)

CreationResult = _reflection.GeneratedProtocolMessageType('CreationResult', (_message.Message,), {
  'DESCRIPTOR' : _CREATIONRESULT,
  '__module__' : 'feature_gate_pb2'
  # @@protoc_insertion_point(class_scope:featuregate.CreationResult)
  })
_sym_db.RegisterMessage(CreationResult)

OpennessResult = _reflection.GeneratedProtocolMessageType('OpennessResult', (_message.Message,), {
  'DESCRIPTOR' : _OPENNESSRESULT,
  '__module__' : 'feature_gate_pb2'
  # @@protoc_insertion_point(class_scope:featuregate.OpennessResult)
  })
_sym_db.RegisterMessage(OpennessResult)

AddResult = _reflection.GeneratedProtocolMessageType('AddResult', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESULT,
  '__module__' : 'feature_gate_pb2'
  # @@protoc_insertion_point(class_scope:featuregate.AddResult)
  })
_sym_db.RegisterMessage(AddResult)

RemoveResult = _reflection.GeneratedProtocolMessageType('RemoveResult', (_message.Message,), {
  'DESCRIPTOR' : _REMOVERESULT,
  '__module__' : 'feature_gate_pb2'
  # @@protoc_insertion_point(class_scope:featuregate.RemoveResult)
  })
_sym_db.RegisterMessage(RemoveResult)

FeatureResult = _reflection.GeneratedProtocolMessageType('FeatureResult', (_message.Message,), {
  'DESCRIPTOR' : _FEATURERESULT,
  '__module__' : 'feature_gate_pb2'
  # @@protoc_insertion_point(class_scope:featuregate.FeatureResult)
  })
_sym_db.RegisterMessage(FeatureResult)

BatchCheckResult = _reflection.GeneratedProtocolMessageType('BatchCheckResult', (_message.Message,), {
  'DESCRIPTOR' : _BATCHCHECKRESULT,
  '__module__' : 'feature_gate_pb2'
  # @@protoc_insertion_point(class_scope:featuregate.BatchCheckResult)
  })
_sym_db.RegisterMessage(BatchCheckResult)



_FEATUREGATE = _descriptor.ServiceDescriptor(
  name='FeatureGate',
  full_name='featuregate.FeatureGate',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=583,
  serialized_end=1175,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateFeature',
    full_name='featuregate.FeatureGate.CreateFeature',
    index=0,
    containing_service=None,
    input_type=_FEATURE,
    output_type=_CREATIONRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CheckOpenness',
    full_name='featuregate.FeatureGate.CheckOpenness',
    index=1,
    containing_service=None,
    input_type=_FEATURENAME,
    output_type=_OPENNESSRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AddGuildFeature',
    full_name='featuregate.FeatureGate.AddGuildFeature',
    index=2,
    containing_service=None,
    input_type=_FEATUREADDITION,
    output_type=_ADDRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveGuildFeature',
    full_name='featuregate.FeatureGate.RemoveGuildFeature',
    index=3,
    containing_service=None,
    input_type=_FEATUREREMOVAL,
    output_type=_REMOVERESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CheckGuildFeature',
    full_name='featuregate.FeatureGate.CheckGuildFeature',
    index=4,
    containing_service=None,
    input_type=_GUILDFEATURE,
    output_type=_FEATURERESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='BatchCheckGuildFeatures',
    full_name='featuregate.FeatureGate.BatchCheckGuildFeatures',
    index=5,
    containing_service=None,
    input_type=_BATCHCHECK,
    output_type=_BATCHCHECKRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetFeatures',
    full_name='featuregate.FeatureGate.GetFeatures',
    index=6,
    containing_service=None,
    input_type=_FEATURELIST,
    output_type=_FEATURE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetGuildFeatures',
    full_name='featuregate.FeatureGate.GetGuildFeatures',
    index=7,
    containing_service=None,
    input_type=_GUILD,
    output_type=_FEATURE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FEATUREGATE)

DESCRIPTOR.services_by_name['FeatureGate'] = _FEATUREGATE

# @@protoc_insertion_point(module_scope)
