apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit
  labels:
    app: rabbit
spec:
  selector:
    matchLabels:
      app: rabbit
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
        - name: rabbit
          image: rabbit-image
          envFrom:
          - secretRef:
              name: architus-secret
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: rabbit
  ports:
  - port: 5672
    targetPort: 5672