apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  labels:
    app: manager
spec:
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      containers:
        - name: manager
          image: "{{prefix}}manager:{{tag}}"
          envFrom:
          - secretRef:
              name: architus-secret
          volumeMounts:
            - name: manager-persistent-storage
              mountPath: /app/current_migration
      volumes:
        - name: manager-persistent-storage
          persistentVolumeClaim:
            claimName: manager-claim
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: manager
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: manager
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: manager-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: hdd-storage
  resources:
    requests:
      storage: 100Gi
