version: "3"
services:
  shard:
    image: ${PREFIX:-}shard:${TAG:-latest}
    build:
      context: ../
      dockerfile: ./shard/Dockerfile
  api:
    image: ${PREFIX:-}api:${TAG:-latest}
    build:
      context: ../
      dockerfile: ./api/Dockerfile
  gateway:
    image: ${PREFIX:-}gateway:${TAG:-latest}
    build:
      context: ../
      dockerfile: ./gateway/Dockerfile
  postgres:
    image: ${PREFIX:-}db:${TAG:-latest}
    build:
      context: ../
      dockerfile: ./db/Dockerfile
  dbmanager:
    image: ${PREFIX:-}dbmanager:${TAG:-latest}
    build: ../dbmanager
  manager:
    image: ${PREFIX:-}manager:${TAG:-latest}
    build:
      context: ../
      dockerfile: ./manager/Dockerfile
  rabbit:
    image: ${PREFIX:-}rabbit:${TAG:-latest}
    build:
      context: ../
      dockerfile: ./rabbitmq/Dockerfile
  feature-gate:
    image: ${PREFIX:-}feature-gate:${TAG:-latest}
    build:
      context: ../
      dockerfile: ./feature-gate/Dockerfile
  starlark-reactor:
    image: ${PREFIX:-}starlark-reactor:${TAG:-latest}
    build:
      context: ../
      dockerfile: ./starlark-reactor/Dockerfile
