// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package starlarkreactor

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StarlarkReactorClient is the client API for StarlarkReactor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StarlarkReactorClient interface {
	RunStarlarkScript(ctx context.Context, in *StarlarkScript, opts ...grpc.CallOption) (*ScriptOutput, error)
}

type starlarkReactorClient struct {
	cc grpc.ClientConnInterface
}

func NewStarlarkReactorClient(cc grpc.ClientConnInterface) StarlarkReactorClient {
	return &starlarkReactorClient{cc}
}

func (c *starlarkReactorClient) RunStarlarkScript(ctx context.Context, in *StarlarkScript, opts ...grpc.CallOption) (*ScriptOutput, error) {
	out := new(ScriptOutput)
	err := c.cc.Invoke(ctx, "/starlarkreactor.StarlarkReactor/RunStarlarkScript", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StarlarkReactorServer is the server API for StarlarkReactor service.
// All implementations must embed UnimplementedStarlarkReactorServer
// for forward compatibility
type StarlarkReactorServer interface {
	RunStarlarkScript(context.Context, *StarlarkScript) (*ScriptOutput, error)
	mustEmbedUnimplementedStarlarkReactorServer()
}

// UnimplementedStarlarkReactorServer must be embedded to have forward compatible implementations.
type UnimplementedStarlarkReactorServer struct {
}

func (UnimplementedStarlarkReactorServer) RunStarlarkScript(context.Context, *StarlarkScript) (*ScriptOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunStarlarkScript not implemented")
}
func (UnimplementedStarlarkReactorServer) mustEmbedUnimplementedStarlarkReactorServer() {}

// UnsafeStarlarkReactorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StarlarkReactorServer will
// result in compilation errors.
type UnsafeStarlarkReactorServer interface {
	mustEmbedUnimplementedStarlarkReactorServer()
}

func RegisterStarlarkReactorServer(s grpc.ServiceRegistrar, srv StarlarkReactorServer) {
	s.RegisterService(&StarlarkReactor_ServiceDesc, srv)
}

func _StarlarkReactor_RunStarlarkScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StarlarkScript)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarlarkReactorServer).RunStarlarkScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/starlarkreactor.StarlarkReactor/RunStarlarkScript",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarlarkReactorServer).RunStarlarkScript(ctx, req.(*StarlarkScript))
	}
	return interceptor(ctx, in, info, handler)
}

// StarlarkReactor_ServiceDesc is the grpc.ServiceDesc for StarlarkReactor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StarlarkReactor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "starlarkreactor.StarlarkReactor",
	HandlerType: (*StarlarkReactorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunStarlarkScript",
			Handler:    _StarlarkReactor_RunStarlarkScript_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lib/ipc/proto/starlark-reactor.proto",
}
