# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import lib.ipc.starlark_reactor_pb2 as proto_dot_starlark__reactor__pb2


class StarlarkReactorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunStarlarkScript = channel.unary_unary(
                '/starlarkreactor.StarlarkReactor/RunStarlarkScript',
                request_serializer=proto_dot_starlark__reactor__pb2.StarlarkScript.SerializeToString,
                response_deserializer=proto_dot_starlark__reactor__pb2.ScriptOutput.FromString,
                )


class StarlarkReactorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunStarlarkScript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StarlarkReactorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunStarlarkScript': grpc.unary_unary_rpc_method_handler(
                    servicer.RunStarlarkScript,
                    request_deserializer=proto_dot_starlark__reactor__pb2.StarlarkScript.FromString,
                    response_serializer=proto_dot_starlark__reactor__pb2.ScriptOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'starlarkreactor.StarlarkReactor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StarlarkReactor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunStarlarkScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/starlarkreactor.StarlarkReactor/RunStarlarkScript',
            proto_dot_starlark__reactor__pb2.StarlarkScript.SerializeToString,
            proto_dot_starlark__reactor__pb2.ScriptOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
