# Create minimal deployment
# with just the service binary included

FROM ubuntu:hirsute
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -q \
    && apt-get install -y -q "libssl1.1" "tini" "ca-certificates" \
    && rm -rf /var/lib/apt/lists/*
COPY logs/gateway-normalize/target/debug/logs-gateway-normalize /usr/bin/logs-gateway-normalize
COPY logs/gateway-normalize/config.toml /etc/architus/config.toml
ENV RUST_BACKTRACE=1
