apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-gate
  labels:
    app: feature-gate
spec:
  selector:
    matchLabels:
      app: feature-gate
  template:
    metadata:
      labels:
        app: feature-gate
    spec:
      containers:
        - name: feature-gate
          image: feature-gate-image
          env:
            - name: FEATURE_GATE_CONFIG_DATABASE__USER_NAME
              valueFrom:
                secretKeyRef:
                  name: architus-secret
                  key: db_user
            - name: FEATURE_GATE_CONFIG_DATABASE__USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: architus-secret
                  key: db_pass
---
apiVersion: v1
kind: Service
metadata:
  name: feature-gate
  namespace: default
spec:
  type: NodePort
  selector:
    app: feature-gate
  ports:
    - port: 50555
      targetPort: 50555
