# Create minimal deployment
# with just the service binary included

FROM debian:buster-slim
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update -q \
    && apt-get install -y -q "libssl1.1" "tini" \
    && rm -rf /var/lib/apt/lists/*
COPY logs/search/target/debug/logs-search /usr/bin/logs-search
COPY logs/search/config.toml /etc/architus/config.toml
ENV RUST_BACKTRACE=1
ENTRYPOINT ["/usr/bin/logs-search", "/etc/architus/config.toml"]
