// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: sandbox.proto

package sandbox;

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type StarlarkScript struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Script         string   `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`
	TriggerMessage string   `protobuf:"bytes,2,opt,name=trigger_message,json=triggerMessage,proto3" json:"trigger_message,omitempty"`
	Author         string   `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Count          uint64   `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Captures       []string `protobuf:"bytes,5,rep,name=captures,proto3" json:"captures,omitempty"`
	Arguments      []string `protobuf:"bytes,6,rep,name=arguments,proto3" json:"arguments,omitempty"`
}

func (x *StarlarkScript) Reset() {
	*x = StarlarkScript{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sandbox_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StarlarkScript) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarlarkScript) ProtoMessage() {}

func (x *StarlarkScript) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarlarkScript.ProtoReflect.Descriptor instead.
func (*StarlarkScript) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{0}
}

func (x *StarlarkScript) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *StarlarkScript) GetTriggerMessage() string {
	if x != nil {
		return x.TriggerMessage
	}
	return ""
}

func (x *StarlarkScript) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *StarlarkScript) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *StarlarkScript) GetCaptures() []string {
	if x != nil {
		return x.Captures
	}
	return nil
}

func (x *StarlarkScript) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type ScriptOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Output string `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Errno  uint64 `protobuf:"varint,3,opt,name=errno,proto3" json:"errno,omitempty"`
}

func (x *ScriptOutput) Reset() {
	*x = ScriptOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sandbox_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScriptOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptOutput) ProtoMessage() {}

func (x *ScriptOutput) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptOutput.ProtoReflect.Descriptor instead.
func (*ScriptOutput) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{1}
}

func (x *ScriptOutput) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ScriptOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ScriptOutput) GetErrno() uint64 {
	if x != nil {
		return x.Errno
	}
	return 0
}

var File_sandbox_proto protoreflect.FileDescriptor

var file_sandbox_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x22, 0xb9, 0x01, 0x0a, 0x0e, 0x53, 0x74, 0x61,
	0x72, 0x6c, 0x61, 0x72, 0x6b, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x74, 0x72,
	0x69, 0x67, 0x67, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61,
	0x70, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61,
	0x70, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x22, 0x52, 0x0a, 0x0c, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x32, 0x50, 0x0a, 0x07, 0x53, 0x61, 0x6e, 0x64,
	0x62, 0x6f, 0x78, 0x12, 0x45, 0x0a, 0x11, 0x52, 0x75, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x6c, 0x61,
	0x72, 0x6b, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x12, 0x17, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62,
	0x6f, 0x78, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x6c, 0x61, 0x72, 0x6b, 0x53, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x1a, 0x15, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x53, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_sandbox_proto_rawDescOnce sync.Once
	file_sandbox_proto_rawDescData = file_sandbox_proto_rawDesc
)

func file_sandbox_proto_rawDescGZIP() []byte {
	file_sandbox_proto_rawDescOnce.Do(func() {
		file_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(file_sandbox_proto_rawDescData)
	})
	return file_sandbox_proto_rawDescData
}

var file_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sandbox_proto_goTypes = []interface{}{
	(*StarlarkScript)(nil), // 0: sandbox.StarlarkScript
	(*ScriptOutput)(nil),   // 1: sandbox.ScriptOutput
}
var file_sandbox_proto_depIdxs = []int32{
	0, // 0: sandbox.Sandbox.RunStarlarkScript:input_type -> sandbox.StarlarkScript
	1, // 1: sandbox.Sandbox.RunStarlarkScript:output_type -> sandbox.ScriptOutput
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sandbox_proto_init() }
func file_sandbox_proto_init() {
	if File_sandbox_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sandbox_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StarlarkScript); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sandbox_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScriptOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sandbox_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sandbox_proto_goTypes,
		DependencyIndexes: file_sandbox_proto_depIdxs,
		MessageInfos:      file_sandbox_proto_msgTypes,
	}.Build()
	File_sandbox_proto = out.File
	file_sandbox_proto_rawDesc = nil
	file_sandbox_proto_goTypes = nil
	file_sandbox_proto_depIdxs = nil
}
