apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: "{{prefix}}db:{{tag}}"
          envFrom:
          - secretRef:
              name: architus-secret
          volumeMounts:
            - name: db-persistent-storage
              mountPath: /app/current_migration
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: db-persistent-storage
          persistentVolumeClaim:
            claimName: db-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: hdd-storage
  resources:
    requests:
      storage: 400Gi