# Ignore everything
**

# Include this service's source
!shard-rs/src
!shard-rs/Cargo.lock
!shard-rs/Cargo.toml
!shard-rs/build.rs
!shard-rs/config.default.toml

# Include config-backoff-rs
!lib/config-backoff-rs/src
!lib/config-backoff-rs/Cargo.toml
