apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox
  labels:
    app: sandbox
spec:
  selector:
    matchLabels:
      app: sandbox
  template:
    metadata:
      labels:
        app: sandbox
    spec:
      containers:
        - name: sandbox
          image: "{{prefix}}sandbox:{{tag}}"
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
          envFrom:
          - secretRef:
              name: architus-secret
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: sandbox
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: sandbox
  ports:
  - protocol: TCP
    port: 1337
    targetPort: 1337
