apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  labels:
    app: manager
spec:
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      containers:
        - name: manager
          image: manager-image
          envFrom:
          - secretRef:
              name: architus-secret
---
apiVersion: v1
kind: Service
metadata:
  name: manager
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: manager
  ports:
  - port: 50051
    targetPort: 50051